### ISSUE TITLE
Source extraction failed for file(s) with certain extended attributes

### ISSUE THREAD

**Issue by Staudey** [getsolus/solbuild#126]
Trying to update `asio` to version 1.34.2 I ran into the following error:

```
 ✓  Now starting build package=asio
[Warning] ypkg-build should be run via fakeroot, not as real root user
[Info] Building asio-1.34.2
[Build] Building native package
[Source] Extracting source
asio-1.34.2/doc/proactor.png: Cannot restore extended attributes on this file system.: Unknown error -1
bsdtar: Error exit delayed from previous errors.
[Source] Failed to extract asio-1.34.2.tar.gz
[Source] Cannot extract sources
 ✗  Failed to build packages err="Failed to start build of package, reason: exit status 1\n"
task: Failed to run task "build": exit status 1
```

Building with plain `ypkg` works fine. Also extracting the tarball with `bsdtar` seems to cause no issues. Potentially interesting messages when manually extracting the tarball during the package build (using `tar --strip-components=1 -xf $sources/asio-%version%.tar.gz`):

```bash
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
```
The last one is repeated many times.

`package.yml` to reproduce:

```yaml
name       : asio
version    : 1.34.2
release    : 5
source     :
    - https://sourceforge.net/projects/asio/files/asio/1.34.2%20%28Stable%29/asio-1.34.2.tar.gz : 30ab18dc58b864f4087967a47b2645c34090b419faab724598dcea07feb84193
license    : BSL-1.0
homepage   : http://think-async.com/Asio/
component  : programming.library
summary    : Cross-platform C++ library for network and low-level I/O programming
description: |
    Asio is a cross-platform C++ library for network and low-level I/O programming that provides developers with a consistent asynchronous model using a modern C++ approach
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
patterns   :
    - /*
```
