### ISSUE TITLE
Consider another imports sorting method

### ISSUE THREAD

**Issue by livingsilver94** [getsolus/solbuild#13]
Solus sorts import paths alphabetically, with no new line between stdlib and third-party modules.
Since the de-facto standard language server for Go is gopls, which doesn't support `goimports`-style imports, I think it's just easier for everyone using an IDE to let `gopls` format imports the way it likes.

Otherwise, people should set [trickery like this](https://github.com/microsoft/vscode-go/issues/2650) or disable automatic formatting entirely, which is not a good idea IMO.

This issue could potentially be applied to all Solus Go projects.

**Comment by silkeh** [comment]
#35 introduced configuration to enforce import sorting using [gci](https://github.com/daixiang0/gci) in `.golangci-lint.yaml`:

```yaml
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/getsolus/solbuild)
```

This can automatically be applied locally using:

```
gci write . -s standard -s default -s 'prefix(github.com/getsolus/solbuild)'
```
